2024-10-03 23:09:41,197 INFO    MainThread:3252 [wandb_setup.py:_flush():68] Configure stats pid to 3252
2024-10-03 23:09:41,197 INFO    MainThread:3252 [wandb_setup.py:_flush():68] Loading settings from C:\Users\shanthod\.config\wandb\settings
2024-10-03 23:09:41,197 INFO    MainThread:3252 [wandb_setup.py:_flush():68] Loading settings from C:\Users\shanthod\OneDrive - Singapore Management University\Desktop\codes\wandb\settings
2024-10-03 23:09:41,197 INFO    MainThread:3252 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2024-10-03 23:09:41,197 INFO    MainThread:3252 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program_relpath': 'main.py', 'program': 'C:\\Users\\shanthod\\OneDrive - Singapore Management University\\Desktop\\codes\\main.py'}
2024-10-03 23:09:41,197 INFO    MainThread:3252 [wandb_init.py:_log_setup():492] Logging user logs to C:\Users\shanthod\OneDrive - Singapore Management University\Desktop\codes\wandb\run-20241003_230941-9nv8jmyi\logs\debug.log
2024-10-03 23:09:41,197 INFO    MainThread:3252 [wandb_init.py:_log_setup():493] Logging internal logs to C:\Users\shanthod\OneDrive - Singapore Management University\Desktop\codes\wandb\run-20241003_230941-9nv8jmyi\logs\debug-internal.log
2024-10-03 23:09:41,197 INFO    MainThread:3252 [wandb_init.py:init():532] calling init triggers
2024-10-03 23:09:41,197 INFO    MainThread:3252 [wandb_init.py:init():538] wandb.init called with sweep_config: {}
config: {}
2024-10-03 23:09:41,197 INFO    MainThread:3252 [wandb_init.py:init():554] re-initializing run, found existing run on stack: cdvaxk9z
2024-10-03 23:09:41,197 INFO    MainThread:3252 [wandb_run.py:_finish():1854] finishing run shan_proj/ssl-relation-prediction/cdvaxk9z
2024-10-03 23:09:41,197 INFO    MainThread:3252 [jupyter.py:save_history():449] not saving jupyter history
2024-10-03 23:09:41,197 INFO    MainThread:3252 [jupyter.py:save_ipynb():379] not saving jupyter notebook
2024-10-03 23:09:41,197 INFO    MainThread:3252 [wandb_init.py:_jupyter_teardown():420] cleaning up jupyter logic
2024-10-03 23:09:41,202 INFO    MainThread:3252 [wandb_run.py:_atexit_cleanup():2083] got exitcode: 0
2024-10-03 23:09:41,203 INFO    MainThread:3252 [wandb_run.py:_restore():2066] restore
2024-10-03 23:09:41,203 INFO    MainThread:3252 [wandb_run.py:_restore():2072] restore done
2024-10-03 23:12:11,306 INFO    MainThread:3252 [wandb_init.py:init():588] starting backend
2024-10-03 23:12:11,306 INFO    MainThread:3252 [wandb_init.py:init():592] setting up manager
2024-10-03 23:12:11,312 INFO    MainThread:3252 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn, using: spawn
2024-10-03 23:12:11,315 INFO    MainThread:3252 [wandb_init.py:init():599] backend started and connected
2024-10-03 23:12:11,327 INFO    MainThread:3252 [wandb_run.py:_label_probe_notebook():1203] probe notebook
2024-10-03 23:12:11,327 INFO    MainThread:3252 [wandb_run.py:_label_probe_notebook():1213] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-10-03 23:12:11,327 INFO    MainThread:3252 [wandb_init.py:init():687] updated telemetry
2024-10-03 23:12:11,338 INFO    MainThread:3252 [wandb_init.py:init():727] communicating run to backend with 60.0 second timeout
